name: Confluence Publisher coba

on:
  push:
     tags: 
       - 'v*-dummytw'
jobs:
    build:
  
      runs-on: ubuntu-latest
  
      steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        env:
          username: ${{ secrets.USER_ID }}
          password: ${{ secrets.PASSWORD_ID }}
        run: mvn org.sahli.asciidoc.confluence.publisher:asciidoc-confluence-publisher-maven-plugin:publish --file docs/pom.xml -Dusername=$username -Dpassword=$password